# Generated by Django 5.2.3 on 2025-07-28 23:09

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datastream',
            fields=[
                ('datastream_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('observed_property', models.CharField(max_length=100)),
                ('release_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('observation_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('observed_value', models.FloatField(help_text='The value of the observation')),
                ('release_status', models.BooleanField(default=False)),
                ('datastream_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='samplelocations.datastream', verbose_name='related datastream')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('coordinate', django.contrib.gis.db.models.fields.PointField(dim=3, srid=4326)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'db_table_comment': "This table stores point locations on the earth's surface",
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('sample_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sample_date', models.DateTimeField()),
                ('sample_notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('sensor_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=50, null=True)),
                ('install_date', models.DateTimeField(blank=True, null=True)),
                ('model', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroundwaterLevelObservation',
            fields=[
                ('groundwater_level_observation_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('observation_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='groundwater_level_observations', to='samplelocations.observation', verbose_name='related observation')),
            ],
            bases=('samplelocations.observation',),
        ),
        migrations.CreateModel(
            name='Location_Thing_Junction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_start', models.DateTimeField()),
                ('effective_end', models.DateTimeField()),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations_things', to='samplelocations.location', verbose_name='related location')),
            ],
            options={
                'db_table_comment': 'Junction table linking Location and Thing models',
            },
        ),
        migrations.AddField(
            model_name='observation',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='samplelocations.sample', verbose_name='related sample'),
        ),
        migrations.AddField(
            model_name='datastream',
            name='sensor_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='datastreams', to='samplelocations.sensor', verbose_name='related sensor'),
        ),
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('thing_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('thing_type', models.CharField(choices=[('W', 'Well'), ('S', 'Spring')], default='W', max_length=2, verbose_name='type of thing')),
                ('release_status', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, help_text='A description of the thing', null=True)),
                ('well_depth_ft', models.FloatField(blank=True, help_text='well depth feet below ground surface', null=True)),
                ('hole_depth_ft', models.FloatField(blank=True, help_text='hole depth feet below ground surface', null=True)),
                ('casing_diameter_ft', models.FloatField(blank=True, help_text='casing diameter in ft', null=True)),
                ('casing_depth_ft', models.FloatField(blank=True, help_text='casing depth feet below ground surface', null=True)),
                ('casing_description', models.CharField(blank=True, max_length=50, null=True)),
                ('construction_notes', models.TextField(blank=True, null=True)),
                ('spring_type', models.CharField(blank=True, max_length=255, null=True)),
                ('location_id', models.ManyToManyField(related_name='things', through='samplelocations.Location_Thing_Junction', to='samplelocations.location', verbose_name='related location')),
            ],
            options={
                'verbose_name': 'Thing',
                'verbose_name_plural': 'Things',
            },
        ),
        migrations.AddField(
            model_name='sample',
            name='thing_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='samplelocations.thing', verbose_name='related thing'),
        ),
        migrations.AddField(
            model_name='location_thing_junction',
            name='thing_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations_things', to='samplelocations.thing', verbose_name='related thing'),
        ),
        migrations.AddField(
            model_name='datastream',
            name='thing_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datastreams', to='samplelocations.thing', verbose_name='related thing'),
        ),
        migrations.AddConstraint(
            model_name='location_thing_junction',
            constraint=models.UniqueConstraint(fields=('location_id', 'thing_id'), name='unique_location_thing'),
        ),
    ]
