# Generated by Django 5.2.3 on 2025-07-11 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samplelocations', '0002_datastream_observation_location_sample_sensor_thing_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='location_thing_junction',
            name='unique_location_thing',
        ),
        migrations.RenameField(
            model_name='datastream',
            old_name='thing',
            new_name='thing_id',
        ),
        migrations.RenameField(
            model_name='location_thing_junction',
            old_name='location',
            new_name='location_id',
        ),
        migrations.RenameField(
            model_name='location_thing_junction',
            old_name='thing',
            new_name='thing_id',
        ),
        migrations.RenameField(
            model_name='observation',
            old_name='datastream',
            new_name='datastream_id',
        ),
        migrations.RenameField(
            model_name='sample',
            old_name='thing',
            new_name='thing_id',
        ),
        migrations.RenameField(
            model_name='thing',
            old_name='location',
            new_name='location_id',
        ),
        migrations.RemoveField(
            model_name='wellthing',
            name='casing_depth',
        ),
        migrations.RemoveField(
            model_name='wellthing',
            name='casing_diameter',
        ),
        migrations.RemoveField(
            model_name='wellthing',
            name='hole_depth',
        ),
        migrations.RemoveField(
            model_name='wellthing',
            name='well_depth',
        ),
        migrations.AddField(
            model_name='wellthing',
            name='casing_depth_ft',
            field=models.FloatField(blank=True, help_text='casing depth feet below ground surface', null=True),
        ),
        migrations.AddField(
            model_name='wellthing',
            name='casing_diameter_ft',
            field=models.FloatField(blank=True, help_text='casing diameter in ft', null=True),
        ),
        migrations.AddField(
            model_name='wellthing',
            name='hole_depth_ft',
            field=models.FloatField(blank=True, help_text='hole depth feet below ground surface', null=True),
        ),
        migrations.AddField(
            model_name='wellthing',
            name='well_depth_ft',
            field=models.FloatField(blank=True, help_text='well depth feet below ground surface', null=True),
        ),
        migrations.AddConstraint(
            model_name='location_thing_junction',
            constraint=models.UniqueConstraint(fields=('location_id', 'thing_id'), name='unique_location_thing'),
        ),
    ]
