# Generated by Django 5.2.3 on 2025-07-11 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samplelocations', '0003_remove_location_thing_junction_unique_location_thing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
